# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# # version format
version: 0.6.0

# branches to build
# branches:
#   # whitelist
#   only:
#     - master
#     - production

#   # blacklist
#   except:
#     - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
# os: Windows Server 2012

image:
  - Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\black

# setting up etc\hosts file
# hosts:
#   queue-server: 127.0.0.1
#   db.server.com: 127.0.0.2

# environment variables
# environment:
#   my_var1: value1
#   my_var2: value2
#   # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
#   my_secure_var1:
#     secure: FW3tJ3fMncxvs58/ifSP7w==

# environment:
#  global:
#    connection_string: server=12;password=13;
#    service_url: https://127.0.0.1:8090
#
#  matrix:
#  - db: mysql
#    provider: mysql
#
#  - db: mssql
#    provider: mssql
#    password:
#      secure: $#(JFDA)jQ@#$

# this is how to allow failing jobs in the matrix
# matrix:
#   allow_failures:
#     - platform: x86
#       configuration: Debug
#     - platform: x64
#       configuration: Release

# enable service required for build/tests
# services:
#   - mssql2012sp1        # start SQL Server 2012 SP1 Express
#   - mssql2012sp1rs      # start SQL Server 2012 SP1 Express and Reporting Services
#   - mssql2008r2sp2      # start SQL Server 2008 R2 SP2 Express
#   - mssql2008r2sp2rs    # start SQL Server 2008 R2 SP2 Express and Reporting Services
#   - iis                 # start IIS
#   - msmq                # start Queuing services

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\Projects
  - mkdir dependencies
  - git clone https://github.com/Tessil/hopscotch-map.git
  - cd hopscotch-map
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:\Projects\dependencies ..
  - cmake --build .
  - cmake --build . --target install
  - cd C:\Projects
  - curl -fsSL -o fmt.zip https://github.com/fmtlib/fmt/releases/download/7.1.3/fmt-7.1.3.zip
  - 7z x fmt.zip
  - cd fmt-7.1.3
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:\Projects\dependencies -DFMT_TEST=NO ..
  - cmake --build .
  - cmake --build . --target install
  - cd C:\Projects
  - git clone https://github.com/nlohmann/json.git
  - cd json
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:\Projects\dependencies -DJSON_BuildTests=OFF ..
  - cmake --build .
  - cmake --build . --target install
  - cd C:\Projects
  - curl -fsSL -o z3.zip https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-win.zip
  - 7z x z3.zip
  - move z3-4.8.10-x64-win z3
  - curl -fsSL -o catch.zip https://github.com/catchorg/Catch2/archive/refs/tags/v2.13.6.zip
  - 7z x catch.zip
  - cd Catch2-2.13.6
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=C:\Projects\dependencies -DBUILD_TESTING=OFF ..
  - cmake --build .
  - cmake --build . --target install

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64

# # scripts to run before build
# before_build:

# # scripts to run after build
# after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd C:\Projects\black
  - mkdir build
  - cd build
  - set CC=cl
  - set CXX=cl
  - cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:\Projects\dependencies \
    -DCMAKE_BUILD_TYPE=Release -DENABLE_FORMULAS_TESTS=NO \
    -DZ3_LIBRARY=C:\Projects\z3\bin\libz3.lib \
    -DZ3_INCLUDE_DIR=C:\Projects\z3\include ..
  - cmake --build .
  - copy C:\Projects\z3\bin\libz3.dll .
  - mkdir C:\BLACK
  - cd C:\
  - copy C:\Projects\black\build\src\lib\black.lib C:\BLACK
  - copy C:\Projects\black\build\black.dll C:\BLACK
  - copy C:\Projects\black\build\black.exe C:\BLACK
  - xcopy C:\Projects\black\src\lib\include C:\BLACK\include\ /E /H
  - copy C:\Projects\z3\bin\libz3.dll C:\BLACK
  - 7z a -tzip black-{version}-win-x64.zip C:\BLACK
  - move black-{version}-win-x64.zip C:\Projects\black

# to disable automatic builds
#build: off

# # scripts to run before tests
# before_test:

# # scripts to run after tests
# after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - cd C:\projects\black\build
  - ctest --output-on-failure

# to disable automatic tests 
#test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: black-{version}-win-x64.zip
