task:
  matrix:
    - name: Fedora 29 (g++ 8.3)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 29
    - name: Fedora 30 (g++ 9.2)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 30
    - name: Fedora 31 (g++ 9.2)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 31
    - name: Ubuntu 18.04 (gcc-8.3)
      container:
        dockerfile: docker/Dockerfile.ubuntu
        docker_arguments:
          VERSION: 18.04
          GCC_VERSION: 8
    - name: Ubuntu 20.04 (gcc-9.3)
      container:
        dockerfile: docker/Dockerfile.ubuntu
        docker_arguments:
          VERSION: 20.04
          GCC_VERSION: 9
      environment:
        COVERALLS_REPO_TOKEN: "ENCRYPTED\
        [c7a69f469678bfc6fd9f1e9a0ab2d77e8df79c84c8f38491bb7fc0a185ddcd34cbf3\
        eeefdc521bc5e27abc4e8a4b564d]"
  download_dependencies_script:
    - ./download-mathsat.sh
  debug_build_script:
    - mkdir -p build/debug && cd build/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON ../..
    - make -j2
  release_build_script:
    - mkdir -p build/release && cd build/release
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j2
  test_script:
    - cd build/release && ctest -R black
  coverage_script:
    - cd build/debug && ctest && cd ../..
    - if [ "$COVERALLS_REPO_TOKEN" ]; then coveralls --gcov /usr/bin/gcov-${GCC_VERSION} -b build/debug --exclude external --exclude tests --exclude build; fi

task:
  name: macOS (Apple clang)
  osx_instance:
    image: catalina-base
  download_dependencies_script:
    - brew install cmake gmp wget
    - ./download-mathsat.sh
  debug_build_script:
    - mkdir -p build/debug && cd build/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - make -j2
  release_build_script:
    - mkdir -p build/release && cd build/release
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j2
  test_script:
    - cd build/release && ctest -R black
