task:
  matrix:
    - name: Fedora 29 (g++ 8)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 29
    - name: Fedora 30 (g++ 9)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 30
    - name: Fedora 31 (g++ 9)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 31
    - name: Fedora 32 (g++ 10)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 32
    - name: Ubuntu 18.04 (g++ 8)
      container:
        dockerfile: docker/Dockerfile.ubuntu
        docker_arguments:
          VERSION: 18.04
          GCC_VERSION: 8
    - name: Ubuntu 20.04 (g++ 9)
      container:
        dockerfile: docker/Dockerfile.ubuntu
        docker_arguments:
          VERSION: 20.04
          GCC_VERSION: 9
      environment:
        CODECOV_REPO_TOKEN: "ENCRYPTED\
        [f6131f3947378ac741bd50e49a83f7e619100d91f4c4ff79180a508e39c93f07e2a90c\
        17174261dbafebd70c2f150d45]"
  download_dependencies_script:
    - ./download-mathsat.sh
  debug_build_script:
    - mkdir -p build/debug && cd build/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON ../..
    - make -j2
  coverage_script:
    - cd build/debug && ctest && cd ../..
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_REPO_TOKEN
  release_build_script:
    - mkdir -p build/release && cd build/release
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j2
  test_script:
    - cd build/release && ctest -R black

task:
  name: macOS (Apple clang)
  osx_instance:
    image: catalina-base
  download_dependencies_script:
    - brew install cmake gmp wget
    - ./download-mathsat.sh
  debug_build_script:
    - mkdir -p build/debug && cd build/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - make -j2
  release_build_script:
    - mkdir -p build/release && cd build/release
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j2
  test_script:
    - cd build/release && ctest -R black
