task:
  matrix:
    - name: Fedora 29 (g++ 8.3)
      container:
        dockerfile: docker/Dockerfile.fedora
        docker_arguments:
          VERSION: 29
    - name: Fedora 30 (g++ 9.1)
      container:
        dockerfile: docker/Dockerfile.fedora
  configure_script:
    - git submodule update --init --recursive
    - ./download-mathsat.sh
    - mkdir build && cd build && cmake ..
  build_script:
    - cd build && make -j2
  test_script:
    - cd build && ctest -R black

task:
  matrix:
    - name: Ubuntu 18.04 (gcc-8.3)
      env:
        CC: gcc-8
        CXX: g++-8
    - name: Ubuntu 18.04 (gcc-9.1)
      env:
        CC: gcc-9
        CXX: g++-9
  container:
    dockerfile: docker/Dockerfile.ubuntu
  configure_script:
    - git submodule update --init --recursive
    - ./download-mathsat.sh
    - mkdir build && cd build && cmake ..
  build_script:
    - cd build && make -j2
  test_script:
    - cd build && ctest -R black

task:
  name: macOS Mojave (Apple clang)
  osx_instance:
    image: mojave-base
  setup_script:
    - brew install cmake gmp wget
  configure_script:
    - git submodule update --init --recursive
    - ./download-mathsat.sh
    - mkdir build && cd build && cmake ..
  build_script:
    - cd build && make -j2
  test_script:
    - cd build && ctest -R black
