ARG VERSION=rolling
FROM ubuntu:$VERSION

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y make cmake gdb gcc g++ && \
    apt-get install -y git git-lfs python3 python-is-python3

RUN apt-get update && \
    apt-get install -y libfmt-dev libimmer-dev catch2 libz3-dev libcvc5-dev

ENTRYPOINT ["/usr/bin/env", "--"]
